### PR TITLE
V1.3 Filter by Tags

### LINKED ISSUE #117: Add alphanumeric check for filter as names are alphanumeric.
- a step further to throw `ParseException` if key phrase is not a alphanumeric phrase? Can do this in `parse` of `FilterCommand` utilising `ParserUtil`. This is a optional step to improve AB3 imo.

_Originally posted by @UdhayaShan1 in https://github.com/AY2324S2-CS2103T-W10-1/tp/pull/104#pullrequestreview-1941377997_

### LINKED ISSUE #167: Filter command - Make tags not case sensitive

### LINKED ISSUE #169: Filter by tag

### LINKED ISSUE #171: Add testing for filter by tag

### PR DESCRIPTION
**Pull request by jyztintan**
# Description
This PR introduces tag-based filtering functionality in our application. 

# Key Changes
- Implement Filter by Tag: Introduced the ability to filter entities based on tags
- Implement filter by **multiple** tags
- Create TagsMatchPredicateTest

# Bug Fixes:
- Fix Invalid Tag Error Handling: Addressed a bug where errors were not being thrown as expected for invalid tag inputs, ensuring the application behaves predictably in error scenarios
- Fix Prefix Handling: Resolved an issue where the application allowed more than one prefix type in filter queries, which could lead to ambiguous or unintended filtering behavior 

# Testing:
- Add Integration Testing for Filtering by Tags 
- Include More Testing for Filtering by Tags
- Add Testing for Filtering by Invalid Tags
- Developed unit tests for the TagsMatchPredicate class, validating its behavior and logic in isolation 
- Integration testing for FilterParser and RealodexParser to capture new filter by tag functionality

Fix #169, fix #171, fix #167, fix #117

### CODE REVIEW

File: src/main/java/seedu/realodex/model/person/predicates/PredicateProducer.java [hunk 1]
```diff
@@ -35,29 +40,55 @@ public PredicateProducer() {
...
+     *         if the person's tags contain the specified tag(s), and {@code false} otherwise.
+     */
+    public Predicate<Person> createMatchTagsPredicate(List<String> tagStrings) {
+        try {
+            Set<Tag> tagSet = ParserUtil.parseTags(tagStrings);
+            return new TagsMatchPredicate(tagSet);
+        } catch (ParseException e) {
+            assert false;
+        }
+        return null;
```
Comment (appleraincoat) [inline src/main/java/seedu/realodex/model/person/predicates/PredicateProducer.java:90]: did you manage to settle the test for this?

File: src/test/java/seedu/realodex/logic/parser/RealodexParserTest.java [hunk 2]
```diff
@@ -93,6 +97,14 @@ public void parseCommand_filterByRemark() throws Exception {
         assertEquals(new FilterCommand(new RemarkContainsKeyphrasePredicate(keyphrase)), command);
     }
 
+    @Test
```
Comment (appleraincoat) [inline src/test/java/seedu/realodex/logic/parser/RealodexParserTest.java:100]: Great test! Perhaps you can consider adding more tests where the tag set contains only buyer/only seller 🤔

File: src/test/java/seedu/realodex/model/person/predicate/TagsMatchPredicateTest.java [hunk 3]
```diff
@@ -0,0 +1,120 @@
...
+
+import seedu.realodex.model.person.Person;
+import seedu.realodex.model.person.predicates.TagsMatchPredicate;
+import seedu.realodex.model.tag.Tag;
+import seedu.realodex.testutil.PersonBuilder;
+
+
+public class TagsMatchPredicateTest {
+
+    @Test
```
Comment (appleraincoat) [inline src/test/java/seedu/realodex/model/person/predicate/TagsMatchPredicateTest.java:19]: Exhaustively covered all possibilities, nice!

**Review by appleraincoat — APPROVED** [review]
LGTM! Great job on abstractions with the prefixchecker and predicateproducer. Take note of the assertions, just use if-else to catch those cases. 👍

File: src/test/java/seedu/realodex/model/person/predicate/TagsMatchPredicateTest.java [hunk 4]
```diff
@@ -0,0 +1,120 @@
+package seedu.realodex.model.person.predicate;
```
Comment (4llysa) [inline src/test/java/seedu/realodex/model/person/predicate/TagsMatchPredicateTest.java:1]: Great testing!

File: src/main/java/seedu/realodex/model/person/predicates/TagsMatchPredicate.java [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+
+    public TagsMatchPredicate(Set<Tag> tagSet) {
+        this.tagSet = tagSet;
+    }
+
+    @Override
+    public boolean test(Person person) {
+        Set<Tag> personTags = person.getTags();
+        return personTags.containsAll(tagSet);
+    }
```
Comment (4llysa) [inline src/main/java/seedu/realodex/model/person/predicates/TagsMatchPredicate.java:25]: Good job on this! It works fine for me and covers all corner cases I could think of.

**Review by 4llysa — APPROVED** [review]

File: src/main/java/seedu/realodex/logic/parser/PrefixChecker.java [hunk 6]
```diff
@@ -54,30 +61,62 @@ public boolean checkEmptyPreamble() {
...
+    /**
+     * Identifies if the given prefix is a special case that is subject to different duplication rules.
+     * For example, tag prefixes are allowed to appear more than once but at most twice
+     * without being considered duplicates.
+     *
+     * @param prefix The {@link Prefix} to be checked.
+     * @return {@code true} if the prefix is a special case, {@code false} otherwise.
+     */
+    public boolean isSpecialCasePrefix(Prefix prefix) {
+        assert(prefix != null);
```
[the remark this answers is not in the document]
Comment (jyztintan) [reply src/main/java/seedu/realodex/logic/parser/PrefixChecker.java:108]: Actually I used it because I only use this within the PrefixChecker class, and everytime I call it, I have already checked that the Prefix is not null. 

Hence, as a programmer, I am _assuming_ that the input here will never be `null` is that okay?

**Comment by jyztintan** [comment]
Fix #117
